name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Run a log message
      run: echo This is my job running tests!
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Clean the build
      run: ./gradlew clean
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: AssembleDebug with Gradle
      run: ./gradlew assembleDebug
      
    - name: Unit tests
      run: ./gradlew test

    - name: Build testing log
      run: echo Tested successfully.
