name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Unit Tests
        run: ./gradlew test

  build:
    needs: [unit_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3.2.0
        with:
          package: 'build-tools;29.0.3'

      - name: Clean the build
        run: ./gradlew clean

      - name: Generate Release APK
        run: ./gradlew assembleRelease

      - name: Sign Android release
        uses: r0adkll/sign-android-release@v1.0.4

        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ALIAS_KEY_PASSWORD }}
        env:
          # override default build-tools version (33.0.0) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"
      - uses: actions/upload-artifact@main
        with:
          name: release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
      - uses: actions/upload-artifact@main
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt

  deploy-firebase: #https://github.com/wzieba/Firebase-Distribution-Github-Action?tab=readme-ov-file
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: release.apk
      - name: upload artifact to Firebase App distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: internal-testers
          # This is the path to the signed release APK, this we can get from `build` Job's log in GitHub Actions
          file: /home/runner/work/android-cicd-githubActions/android-cicd-githubActions/app-release-signed.apk



